version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into ECR
      - aws --version
      - aws sts get-caller-identity
      - aws configure list
      - echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
      - echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Starting build at `date`
      - echo Checking Docker version and info
      - docker version
      - docker info
      - echo "Listing current directory contents:"
      - ls -la
      - echo "Listing ./analytics directory contents:"
      - ls -la ./analytics
      - echo Building the Docker image...
      - docker build -t coworking:$CODEBUILD_BUILD_NUMBER ./analytics
      - docker tag coworking:$CODEBUILD_BUILD_NUMBER $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/coworking:$CODEBUILD_BUILD_NUMBER

  post_build:
    commands:
      - echo Completed build at `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/coworking:$CODEBUILD_BUILD_NUMBER
